### ISSUE TITLE
Unable to configure...

### ISSUE THREAD

**Issue by sixro** [compactcode/open.vim#1]
Hi, I am trying to use a plugin I made years ago.  
I am not sure this plugin is still maintained, but I try anyway :)

I am using it with java and I configured it in this way:
```
  let b:alternate_source_dirs = b:mvnSourceDirectory
  let b:alternate_test_token = "Test"
  let b:alternate_test_token_location = "$"
  let b:alternate_test_dirs = b:mvnTestSourceDirectory
  let b:alternate_enabled = 1
```

where `b:mvnSourceDirectory` is valued as `./src/main/java` and `b:mvnTestSourceDirectory` as `./src/test/java`.

If I run `echo alternate#FindAlternate()`, it shows a path that is correct, because if I use it with a `:e` vim opens that file.  
Unfortunately, if I execute:
```
    :Open(alternate#FindAlternate())
```
The output is:
```
    Nothing to open.
```

Looking into the plugin, it seems that the output of `alternate#FindAlternate()` is empty because I found that `Nothing to open` appears only when `if a:path > string(0)` is `false`.  
Can you help me to understand what's the issue?
Regards
  R

**Comment by compactcode** [comment]
It looks like Open doesn't handle the leading `./` properly in the file path. i.e.

`:call open#Open('Gemfile')` works
`:e ./Gemfile` works
`:call open#Open('./Gemfile')` does not work

As you pointed out it appears that `if a:path > string(0)` returns false for `'./Gemfile'`. The purpose of that line is just to work out if the file exists or not and there is probably a better way to do that in vimscript. Unfortunately I no longer have interest in working with vimscript (will be using lua with neovim going forwards) so I am not motivated to investigate. Happy to review & accept a pull request though if you are keen though.

A workaround would be to change  in your alternate setup to remove the leading `./` i.e. (`./src/main/java` -> `src/main/java`)

**Comment by sixro** [comment]
Thanks @compactcode 
You are right! I changed my plugin as I was adding that `./` as a prefix.  
Now it works, thanks again.
